source :rubygems
gem 'travis-sso', github: 'travis-ci/travis-sso'
gem 'sinatra',    github: 'sinatra/sinatra'
gem 'rack-ssl', '>= 1.3.3'
gem 'coffee-script'
gem 'slim'
gem 'thin', '>= 1.5.1'
gem 'sass'
gem 'rinku'
gem 'rake'