source :rubygems
gem 'travis-sso', github: 'travis-ci/travis-sso'
gem 'sinatra',    github: 'sinatra/sinatra'
gem 'rack-ssl', '>= 1.3.4'
gem 'coffee-script'
gem 'slim'
gem 'thin'
gem 'sass'
gem 'rinku'
gem 'rake', '>= 12.3.3'